name: Analyze, Build, Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Analyze project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.7"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test

  build_apk:
    needs: [test]
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.7"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          name: "Analog Clock ${{ github.ref_name }}"
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
